baseURL = "https://sarathsek.github.io/"
languageCode = "en-us"
title = "Sarath Sek"
theme = "PaperMod"

[menu]

[[menu.main]]
name = "About"
url = "/about/"
weight = 2

[[menu.main]]
name = "Portfolio"
url = "/portfolio/"
weight = 3

[[menu.main]]
name = "Blog"
url = "/blog/"
weight = 4

[[menu.main]]
name = "Experience"
url = "/experience/"
weight = 5


[params.profileMode]
enabled = true
title = "Sarath Sek"
subtitle = """
I am a Data Analyst and AI Specialist student with a background in Mobile Development and Video Game Art, combining technical knowledge with creativity and problem-solving skills. My journey has allowed me to explore software development, data analytics, artificial intelligence, and emerging technologies while continuously expanding my skill set through hands-on projects and academic learning.

I am passionate about transforming data into meaningful insights, developing innovative solutions, and understanding how technology can be used to solve real-world challenges. As I continue growing as a professional, I am committed to learning new tools, improving my analytical abilities, and applying my dedication, curiosity, and creativity to create impactful work in the fields of Data Analytics and Artificial Intelligence.
"""
imageUrl = "/images/profile.png"
imageTitle = "Sarath Sek"
imageWidth = 160
imageHeight = 160

[[params.profileMode.buttons]]
name = "About"
url = "/about/"

[[params.profileMode.buttons]]
name = "Blog"
url = "/blog/"

[[params.profileMode.buttons]]
name = "Experience"
url = "/experience/"

[[params.profileMode.buttons]]
name = "Portfolio"
url = "/portfolio/"

[[params.socialIcons]]
name = "github"
url = "https://github.com/SarathSek"

[[params.socialIcons]]
name = "linkedin"
url = "https://linkedin.com/in/sarath-sek"

[[params.socialIcons]]
name = "x"
url = "https://x.com/yourusername"

disableThemeToggle = true


[params]
ShowBreadCrumbs = false
ShowReadingTime = false
ShowShareButtons = false
ShowPostNavLinks = false
ShowCodeCopyButtons = false

mainSections = ["blog"]

[markup.goldmark.renderer]
unsafe = true
